---
title: "Lab3-Exploratory_Data_Analysis"
author: "Xuan Huang"
date: "r Sys.Date()"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Steps

## 1. Read in the data

```{r}
install.packages('R.utils')
download.file("https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz", "met_all.gz", method="libcurl", timeout = 60)
met <- data.table::fread("met_all.gz")

```

## 2. Check the dimensions, headers, footers. How many columns, rows are there?

```{r}
dim(met)
head(met)
tail(met)

```
**There are 2377343 rows and 30 colummns.**

## 3. take a look at the variables

```{r}
str(met)
```

## 4. Take a closer look at the key variables.



```{r}
#for count variable, show frequency
table(met$year)
table(met$month)
table(met$hour)

#for continous varibale, show mean, quatiles...
summary(met$temp)
summary(met$elev)
summary(met$temp)

sum(met$elev == 9999.0)

met[met$elev==9999.0] <- NA
summary(met$elev)

met <- met[temp > -40]
met2 <- met[order(temp)]
head(met2$temp)
summary(met2$temp)
hist(met2$temp)
#from the summary of met2's temp and histogram, minimum temp -17.2 not make sense

```
## 5. Check the data against an external data source.
```{r}
met <- met[temp>-15]
met2 <- met[order(temp)]
head(met2)
```


## 6. Calculate summary statistics

```{r}
elev <- met[elev == max(elev)]
summary(elev)



```

