---
title: "Lab4-data-visualization"
author: "Xuan Huang"
date: "2022-09-14"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#library needed
library("tidyverse")
library("ggplot2")
library("leaflet")
library("data.table")
```

## 1. Read in the data

```{r read-data, cache=TRUE}
if (!file.exists("met_all.gz"))
  download.file(
    url = "https://raw.githubusercontent.com/USCbiostats/data-science-data/master/02_met/met_all.gz",
    destfile = "met_all.gz",
    method   = "libcurl",
    timeout  = 60
    )
met <- data.table::fread("met_all.gz")
```

## 2. Prepare the data

```{r create-ymd, cache=TRUE}
#Remove temperatures less than -17C
head(met)
met <- met[met$temp >= -17]

#Make sure there are no missing data in the key variables coded as 9999, 999, etc
summary(met)
#we can see the maximum value fo elev is 9999.0
met <- met[elev == 9999.0, elev := NA]
summary(met)

#Generate a date variable using the functions as.Date()
met[, ymd := as.Date(paste(year, month, day, sep = "-"))]

#Using the data.table::week function, keep the observations of the first week of the month.
met[, table(week(ymd))]
met <- met[ week(ymd) == 31]
```





```{r}
#Compute the mean by station of the variables temp, rh, wind.sp, vis.dist, dew.point, lat, lon, and elev.


met_avg <- met[, .(
  temp = mean(temp, na.rm = T),
  rh = mean(rh, na.rm = T),
  wind.sp = mean(wind.sp, na.rm = T),
  vis.dist = mean(vis.dist, na.rm = T),
  dew.point = mean(dew.point, na.rm = T),
  lat = mean(lat, na.rm = T),
  lon = mean(lon, na.rm = T),
  elev = mean(elev, na.rm = T)
), by = "USAFID"]

met_avg
```
```{r}
#Create a region variable for NW, SW, NE, SE based on lon = -98.00 and lat = 39.71 degrees
met_avg[, region := fifelse(lon >= -98 & lat > 39.71, "NE",
                    fifelse(lon < -98 & lat > 39.71, "NW",
                    fifelse(lon < -98 & lat <= 39.71, "SW", "SE"
                    )))]
table(met_avg$region)
```

```{r}
#Create a categorical variable for elevation as in the lecture slides
met_avg[, elev_cat := fifelse(elev > 252, "high", "low")]
table(met_avg$elev_cat)
```

## 3. Use geom_violin to examine the wind speed and dew point temperature by region


```{r violin}
#wind speed
met_avg[!is.na(elev_cat) & !is.na(region)] %>%  # deal with NA category
ggplot(met_avg, mapping = aes(y = wind.sp, x = 1, color = region, fill = region)) +
  geom_violin() +
  facet_grid(~region)
#dew point
met_avg[!is.na(elev_cat) & !is.na(region)] %>% 
ggplot(met_avg, mapping = aes(y = dew.point, x = 1, color = region, fill = region)) +
  geom_violin() +
  facet_grid(~region)
```


## 4. Use geom_jitter with geom_smooth to examine the association between dew point temperature and wind speed by region

```{r}
met_avg[!is.na(region) & !is.na(wind.sp) & !is.na(dew.point)] %>%
  ggplot(mapping = aes(x = wind.sp, y = dew.point)) +
  geom_point(mapping = aes(color = region)) +
  geom_smooth(formula = y ~x, method = lm, mapping = aes(linetype = region))+
  facet_wrap(~ region, nrow = 2)
```

